replicate_ui.settings:
  type: config_object
  label: 'Replicate UI settings'
  mapping:
    entity_types:
      type: sequence
      sequence:
        type: string
    check_edit_access:
      type: boolean
      label: 'Check original entity edit access'
