name: ReDoc for OpenAPI UI
type: module
description: Provides display of OpenAPI docs using the ReDoc library.
core_version_requirement: ^8.8 || ^9 || ^10
package: OpenAPI
dependencies:
  - openapi_ui:openapi_ui

# Information added by Drupal.org packaging script on 2022-12-06
version: '8.x-1.0-rc4'
project: 'openapi_ui_redoc'
datestamp: 1670344280
